#pragma once

#define PVRTEXLIB_MAJORVERSION 5
#define PVRTEXLIB_MINORVERSION 3
#define PVRTEXLIB_SUBVERSION 0
#define PVRTEXLIB_STRINGVERSION "5.3.0"
#define PVRTEXLIB_FULLVERSIONSTRING "PVRTexLib v5.3.0"
